apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nix-builder-provisioner.fullname" . }}-authorized-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nix-builder-provisioner.labels" . | nindent 4 }}
data:
  authorized_keys: |
    {{- range .Values.authorizedKeys }}
    {{ . }}
    {{- end }}
