{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nix-builder-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nix-builder-provisioner.labels" . | nindent 4 }}
type: Opaque
stringData:
  STORE_HOST: {{ required "store.host is required" .Values.store.host | quote }}
  {{- if .Values.store.hostKey }}
  STORE_HOST_KEY: {{ .Values.store.hostKey | quote }}
  {{- end }}
  {{- if has .Values.provisioner (list "hetzner-ubuntu" "hetzner-snapshot") }}
  HCLOUD_TOKEN: {{ required "hetzner.token is required for hetzner provisioners" .Values.hetzner.token | quote }}
  {{- end }}
{{- end }}
